### ISSUE TITLE
在coreos虚拟机上通过bootstrapper部署k8s master实验

### ISSUE THREAD

**Issue by zhengbo0** [k8sp/sextant#144]
### 在虚拟机上通过bootstrapper部署k8s master实验
需要注意的几个地方:
#### 修改cloud-config-server/template/unisound-ailab/build_config.yml文件
```
bootstrapper: 192.168.8.101
subnet: 192.168.8.0
netmask: 255.255.255.0
iplow: 192.168.8.201
iphigh: 192.168.8.220
routers: [192.168.8.101]
broadcast: 192.168.8.255
nameservers: [192.168.8.101, 8.8.8.8, 8.8.4.4]
domainname: "192.168.8.101"
dockerdomain: "bootstrapper"

nodes:
  - mac: "08:00:27:4a:2d:a1"
    ip: "192.168.8.201"
    ceph_monitor: n
    kube_master: y
    etcd_member: y

ssh_authorized_keys: |1+
    - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDurCHipTNu0FtOpDmQBYiWd/eFsKamKEnPkLW9cIZdb3k4X8irySqFhAS7kd+tU+StuuSSsEqa0wsY6Z7rBQTBljqMpuueJGqlSMFqlDSd4cDw9+dYtc76TWLeMwWdob4RR8XRWCJlT9xVKAVby4gXkoSEYwjbY5FLPzAshpYJeOlfjC4sYUGSGjL8mPL5wKrJIdKf2tTKBpTnkk/cRdmDI66JeD5rV9SYZfOsTmhe76ddF71/Ya42p46AKLkGxxRwKntQY8KioxB4Ml4s+9v2NFcuWqURuy7dW2YYd5VxlurQp6x2vtf79P6W5+eyrgkVADZH0fGxBatdcybF+ybZ root@core-01"
```
####  确保bootstrapper主机名可以正确被解析,修改/etc/hosts
```
192.168.8.101 bootstrapper
```
####  cloud　config　server启动证书问题
默认是没有创建证书的，需要将ca-crt的值和ca-key的值设置为空
```
cloud-config-server -addr ":8081" \
  -dir /bsroot/html/static \
  -cc-template-file /bsroot/config/cloud-config.template \
  -cc-template-url "" \
  -cluster-desc-file /bsroot/config/cluster-desc.yml \
  -cluster-desc-url "" \
  -ca-crt "" \
  -ca-key "" &
# start registry
```
####  docker证书问题
一种方案是配置证书
另外一种是增加bootstrapper服务器的docker drop-in，增加 [Service] Environment=DOCKER_OPTS="--insecure-registry={{ .Dockerdomain }}:5000" 
#### dnsmasp配置文件中绑定了etho0端口，导致pxe client无法检查到pxe server，将前三行注释掉可以解决
```
　#interface=eth0
  #bind-interfaces
  #domain=k8s.baifendian.com
  user=root
  dhcp-range=192.168.8.102,192.168.8.200,255.255.255.0,12h
  log-dhcp
  dhcp-boot=pxelinux.0
  dhcp-option=3,192.168.8.101
  dhcp-option=6,192.168.8.101,8.8.8.8
  no-hosts
  expand-hosts
  no-resolv
  local=/k8s.baifendian.com/
  domain-needed
  dhcp-option=28,192.168.8.255
  #dhcp-option=42,0.0.0.0
  pxe-prompt="Press F8 for menu.", 60
  pxe-service=x86PC, "Install CoreOS from network server", pxelinux
  enable-tftp
  tftp-root=/bsroot/tftpboot

```
#### 通过mac地址作为hostname出现，hostname无法解析的情况,手动添加了/etc/hosts零时解决了，但是问题仍然没有解决
```
08-00-27-4a-2d-a1 certs.d # nslookup 08-00-27-4a-2d-a1
Server:		192.168.8.101
Address:	192.168.8.101#53

Non-authoritative answer:
*** Can't find 08-00-27-4a-2d-a1: No answer
```
查看/etc/resolv.conf 文件内容
```
08-00-27-4a-2d-a1 certs.d # cat  /etc/resolv.conf 
# This file is managed by systemd-resolved(8). Do not edit.
#
# Third party programs must not access this file directly, but
# only through the symlink at /etc/resolv.conf. To manage
# resolv.conf(5) in a different way, replace the symlink by a
# static file or a different symlink.

nameserver 192.168.8.101
nameserver 8.8.8.8
```
