### ISSUE TITLE
vm-cluster auto install k8s异常

### ISSUE THREAD

**Issue by zhengbo0** [k8sp/sextant#190]
journalctl -xef 发现如下异常
```
 Error syncing pod cac8e64f87984643874c6a11735c584e, skipping: [failed to "StartContainer" for "kube-apiserver" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=kube-apiserver pod=kube-controller-08-00-27-4a-2d-a1_default(cac8e64f87984643874c6a11735c584e)"
```
查看k8s api server docker日志，发现service-cluster-ip-range这个值没有取到
`docker logs 976c8f8fbfaa` 
```
 --watch-cache-sizes=[]: List of watch cache sizes for every resource (pods, nodes, etc.), comma separated. The individual override format: resource#size, where size is a number. It takes effect when watch-cache is enabled.
invalid argument "" for --service-cluster-ip-range=: invalid CIDR address:
```
查看cloud config 文件内容 `cat /var/lib/coreos-install/user_data `发现确实没有取到值
```
 - name: kube-apiserver
            image: bootstrapper:5000/hyperkube-amd64:v1.2.0
            command:
              - /hyperkube
              - apiserver
              - --allow-privileged=true
              - --bind-address=0.0.0.0
              - --insecure-bind-address=0.0.0.0
              - --secure-port=443
              - --etcd-servers=http://08-00-27-4a-2d-a1:4001
              - --service-cluster-ip-range=
```
