### ISSUE TITLE
docker 镜像下载异常

### ISSUE THREAD

**Issue by zhengbo0** [k8sp/sextant#259]
下载的脚本如下：
```
DOCKER_IMAGES=("hyperkube" \
    "pause" \
    "flannel" \
    "ingress" \
    "kube2sky" \
    "healthz" \
    "addon_manager" \
    "skydns");
  cd $BSROOT
  len=${#DOCKER_IMAGES[@]}
  for ((i=0;i<len;i++)); do
    DOCKER_IMAGE=`grep "${DOCKER_IMAGES[i]}" $CLUSTER_DESC | awk '{print $2}' | sed 's/ //g' | sed -e 's/^"//' -e 's/"$//'`
    printf "Downloading image ${DOCKER_IMAGE} ..."
    docker pull $DOCKER_IMAGE > /dev/null 2>&1 || { echo "Failed"; exit 1; }
    docker pull $DOCKER_IMAGE
    DOCKER_TAR_FILE=`echo $DOCKER_IMAGE.tar | sed "s/:/_/g" |awk -F'/' '{print $2}'`
    docker save $DOCKER_IMAGE > $DOCKER_TAR_FILE || { echo "Failed"; exit 1; }
    echo "Done"
  done

```
CLUSTER_DESC的配置文件如下
```
images:
  hyperkube: "typhoon1986/hyperkube-amd64:v1.3.6"
  pause: "typhoon1986/pause-amd64:3.0"
  flannel: "typhoon1986/flannel:0.5.5"
  ingress: "yancey1989/nginx-ingress-controller:0.8.3"
  kube2sky: "yancey1989/kube2sky:1.14"
  healthz: "typhoon1986/exechealthz:1.0"
  addon_manager: "yancey1989/kube-addon-manager-amd64:v5.1"
  skydns: "typhoon1986/skydns:latest"

nodes:
  - mac: "08:00:27:4a:2d:a1"
    ceph_monitor: n
    kube_master: y
    etcd_member: y
    ingress: n

```
重点是下面这一句，当${DOCKER_IMAGES[i]}是ingress的时候
```
 DOCKER_IMAGE=`grep "${DOCKER_IMAGES[i]}" $CLUSTER_DESC | awk '{print $2}' | sed 's/ //g' | sed -e 's/^"//' -e 's/"$//'`
```
匹配的字符串有
` ingress: "yancey1989/nginx-ingress-controller:0.8.3"` 还有` ingress: n`
