### ISSUE TITLE
skydns 运行出错

### ISSUE THREAD

**Issue by pineking** [k8sp/sextant#453]
状态显示：
```
 ~/kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                READY     STATUS        RESTARTS   AGE       IP            NODE
default       kube-controller-00-25-90-c0-f7-80   4/4       Running       4          1d        10.10.14.29   00-25-90-c0-f7-80
default       kube-proxy-0c-c4-7a-82-c5-b8        1/1       Running       2          1d        10.10.14.66   0c-c4-7a-82-c5-b8
default       kube-proxy-0c-c4-7a-82-c5-bc        1/1       Running       2          1d        10.10.14.70   0c-c4-7a-82-c5-bc
kube-system   kube-dns-v10-omu55                  2/3       Terminating   0          1d        10.1.14.2     0c-c4-7a-82-c5-b8
```

```
  ~/kubectl logs --namespace=kube-system  kube-dns-v10-omu55 kube2sky
I1217 12:47:11.923964       1 kube2sky.go:462] Etcd server found: http://00-25-90-c0-f7-80:4001
I1217 12:47:13.018857       1 kube2sky.go:529] Using https://10.100.0.1:443 for kubernetes master
I1217 12:47:13.018883       1 kube2sky.go:530] Using kubernetes API <nil>
I1217 12:47:13.019655       1 kube2sky.go:598] Waiting for service: default/kubernetes
I1217 12:47:13.585913       1 kube2sky.go:660] Successfully added DNS record for Kubernetes service.
F1217 12:47:15.372705       1 kube2sky.go:625] Received signal terminated
```

```
 ~/kubectl logs --namespace=kube-system  kube-dns-v10-omu55 skydns
2016/12/17 12:47:12 skydns: falling back to default configuration, could not read from etcd: 100: Key not found (/skydns/config) [606695]
2016/12/17 12:47:12 skydns: metrics enabled on :/metrics
2016/12/17 12:47:12 skydns: ready for queries on cluster.local. for tcp://0.0.0.0:53 [rcache 0]
2016/12/17 12:47:12 skydns: ready for queries on cluster.local. for udp://0.0.0.0:53 [rcache 0]
```

```
 ~/kubectl logs --namespace=kube-system  kube-dns-v10-omu55 healthz
2016/12/17 12:47:14 Worker running nslookup kubernetes.default.svc.cluster.local 127.0.0.1 >/dev/null
```

```
Name:                           kube-dns-v10-omu55
Namespace:                      kube-system
Node:                           0c-c4-7a-82-c5-b8/10.10.14.66
Start Time:                     Sat, 17 Dec 2016 20:47:10 +0800
Labels:                         k8s-app=kube-dns
                                kubernetes.io/cluster-service=true
                                version=v10
Status:                         Terminating (expires Sat, 17 Dec 2016 20:47:45 +0800)
Termination Grace Period:       30s
IP:                             10.1.14.2
Controllers:                    ReplicationController/kube-dns-v10
Containers:
  kube2sky:
    Container ID:       docker://68fa033bf9d3115c8012ef7698100651eb0be598fa778403ee2ae2fc73a8c140
    Image:              bootstrapper:5000/yancey1989/kube2sky:1.14
    Image ID:           docker://sha256:f392390688107db3b4bf889d090f94099468fd0f8ab6d869c65eab73cff939a9
    Port:
    Args:
      --domain=cluster.local
      --etcd-server=http://00-25-90-c0-f7-80:4001
    Limits:
      cpu:      100m
      memory:   50Mi
    Requests:
      cpu:                      100m
      memory:                   50Mi
    State:                      Running
      Started:                  Sat, 17 Dec 2016 20:47:11 +0800
    Ready:                      True
    Restart Count:              0
    Environment Variables:      <none>
  skydns:
    Container ID:       docker://2edb53c8ac290c4687e6ca3c30dbbc318f69222ac5b1473fa7bdb9be8aa56f58
    Image:              bootstrapper:5000/typhoon1986/skydns:latest
    Image ID:           docker://sha256:d607f75848790a569188345a41805c1a33560c60e5d104640eb083a53fa7ca49
    Ports:              53/UDP, 53/TCP
    Args:
      -machines=http://00-25-90-c0-f7-80:4001
      -addr=0.0.0.0:53
      -ns-rotate=false
      -domain=cluster.local.
    Limits:
      cpu:      100m
      memory:   50Mi
    Requests:
      cpu:                      100m
      memory:                   50Mi
    State:                      Running
      Started:                  Sat, 17 Dec 2016 20:47:11 +0800
    Ready:                      False
  Restart Count:              0
    Liveness:                   http-get http://:8080/healthz delay=30s timeout=5s period=10s #success=1 #failure=3
    Readiness:                  http-get http://:8080/healthz delay=30s timeout=5s period=10s #success=1 #failure=3
    Environment Variables:      <none>
  healthz:
    Container ID:       docker://e7cf1d1e63d533633a18c2eeb57bc016db77f2795062867a8d4906325632882b
    Image:              bootstrapper:5000/typhoon1986/exechealthz:1.0
    Image ID:           docker://sha256:95232aaf244d09f8e3d1ed35de25ded309493d9096cd2a17fc36feee5636c76c
    Port:               8080/TCP
    Args:
      -cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1 >/dev/null
      -port=8080
    Limits:
      cpu:      10m
      memory:   20Mi
    Requests:
      cpu:                      10m
      memory:                   20Mi
    State:                      Running
      Started:                  Sat, 17 Dec 2016 20:47:12 +0800
    Ready:                      True
    Restart Count:              0
    Environment Variables:      <none>
Conditions:
  Type          Status
  Initialized   True
  Ready         False
  PodScheduled  True
Volumes:
  etcd-storage:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  default-token-ow6av:
    Type:       Secret (a volume populated by a Secret)
    SecretName: default-token-ow6av
QoS Tier:       Guaranteed
No events.
```

**Comment by pineking** [comment]
```
apiVersion: v1
kind: Service
metadata:
  name: kube-dns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeDNS"
spec:
  selector:
    k8s-app: kube-dns
  clusterIP:  10.100.0.10
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP


---


apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-dns-v10
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    version: v10
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kube-dns
    version: v10
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v10
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: kube2sky
        image: bootstrapper:5000/yancey1989/kube2sky:1.14
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
        args:
        # command = "/kube2sky"
        - --domain=cluster.local
        - --etcd-server=http://00-25-90-c0-f7-80:4001
      - name: skydns
        image: bootstrapper:5000/typhoon1986/skydns:latest
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
        args:
        - -machines=http://00-25-90-c0-f7-80:4001
        - -addr=0.0.0.0:53
        - -ns-rotate=false
        - -domain=cluster.local.
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
      - name: healthz
        image: bootstrapper:5000/typhoon1986/exechealthz:1.0
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
        args:
        - -cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1 >/dev/null
        - -port=8080
        ports:
        - containerPort: 8080
          protocol: TCP
      volumes:
      - name: etcd-storage
        emptyDir: {}
      dnsPolicy: Default  # Don't use cluster DNS.
```
