### ISSUE TITLE
skydns CrashBackOff

### ISSUE THREAD

**Issue by pineking** [k8sp/sextant#454]
skydns 由于 healthz 的检测为 unhealthy，导致 CrashBackOff

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-dns-v10
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    version: v10
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kube-dns
    version: v10
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v10
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: kube2sky
        image: bootstrapper:5000/yancey1989/kube2sky:1.14
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
        args:
        # command = "/kube2sky"
        - --domain=cluster.local
        - --etcd-server=http://00-25-90-c0-f7-c8:4001
      - name: skydns
        image: bootstrapper:5000/typhoon1986/skydns:latest
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
        args:
        - -machines=http://00-25-90-c0-f7-c8:4001
        - -addr=0.0.0.0:53
        - -ns-rotate=false
 - -domain=cluster.local.
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
      - name: healthz
        image: bootstrapper:5000/typhoon1986/exechealthz:1.0
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
        args:
        - -cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1 >/dev/null
        - -port=8080
        ports:
        - containerPort: 8080
          protocol: TCP
      volumes:
      - name: etcd-storage
        emptyDir: {}
      dnsPolicy: Default  # Don't use cluster DNS.
```

```
 ~/kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                READY     STATUS             RESTARTS   AGE       IP            NODE
default       busybox                             1/1       Running            1          1h        10.1.2.2      0c-c4-7a-82-c5-bc
default       kube-controller-00-25-90-c0-f7-80   4/4       Running            4          1d        10.10.14.29   00-25-90-c0-f7-80
default       kube-proxy-0c-c4-7a-82-c5-b8        1/1       Running            2          1d        10.10.14.66   0c-c4-7a-82-c5-b8
default       kube-proxy-0c-c4-7a-82-c5-bc        1/1       Running            10         1d        10.10.14.70   0c-c4-7a-82-c5-bc
kube-system   kube-dns-v10-o4x5m                  1/3       CrashLoopBackOff   19         27m       10.1.2.3      0c-c4-7a-82-c5-bc
```

```
Name:           kube-dns-v10-o4x5m
Namespace:      kube-system
Node:           0c-c4-7a-82-c5-bc/10.10.14.70
Start Time:     Mon, 19 Dec 2016 16:04:03 +0800
Labels:         k8s-app=kube-dns
                kubernetes.io/cluster-service=true
                version=v10
Status:         Running
IP:             10.1.2.3
Controllers:    ReplicationController/kube-dns-v10
Containers:
  kube2sky:
    Container ID:       docker://f2f1f64a93fd8e6ec095a62f8ecc5b3372dd261d762f9b5fdf53df020b2fcd47
    Image:              bootstrapper:5000/yancey1989/kube2sky:1.14
    Image ID:           docker://sha256:f392390688107db3b4bf889d090f94099468fd0f8ab6d869c65eab73cff939a9
    Port:
    Args:
      --domain=cluster.local
      --etcd-server=http://00-25-90-c0-f7-c8:4001
    Limits:
      cpu:      100m
      memory:   50Mi
    Requests:
      cpu:                      100m
      memory:                   50Mi
    State:                      Waiting
      Reason:                   CrashLoopBackOff
    Last State:                 Terminated
      Reason:                   Error
      Exit Code:                255
      Started:                  Mon, 19 Dec 2016 16:27:31 +0800
      Finished:                 Mon, 19 Dec 2016 16:28:26 +0800
    Ready:                      False
    Restart Count:              8
    Environment Variables:      <none>
  skydns:
    Container ID:       docker://5c1e39550657af2f0b9e932ee4c496460c8f8b84cd2b3a62ac0d0d29e8a4c96b
    Image:              bootstrapper:5000/typhoon1986/skydns:latest
    Image ID:           docker://sha256:d607f75848790a569188345a41805c1a33560c60e5d104640eb083a53fa7ca49
    Ports:              53/UDP, 53/TCP
    Args:
      -machines=http://00-25-90-c0-f7-c8:4001
      -addr=0.0.0.0:53
      -ns-rotate=false
      -domain=cluster.local.
    Limits:
      cpu:      100m
      memory:   50Mi
    Requests:
      cpu:                      100m
      memory:                   50Mi
    State:                      Running
      Started:                  Mon, 19 Dec 2016 16:32:13 +0800
    Last State:                 Terminated
      Reason:                   Error
      Exit Code:                2
      Started:                  Mon, 19 Dec 2016 16:31:38 +0800
      Finished:                 Mon, 19 Dec 2016 16:32:13 +0800
    Ready:                      False
    Restart Count:              13
    Liveness:                   http-get http://:8080/healthz delay=30s timeout=5s period=10s #success=1 #failure=3
    Readiness:                  http-get http://:8080/healthz delay=30s timeout=5s period=10s #success=1 #failure=3
    Environment Variables:      <none>
  healthz:
    Container ID:       docker://122ab46babd17f6df78b68b4ede33141656cc66d97aedf4e58838371f480801a
    Image:              bootstrapper:5000/typhoon1986/exechealthz:1.0
    Image ID:           docker://sha256:95232aaf244d09f8e3d1ed35de25ded309493d9096cd2a17fc36feee5636c76c
    Port:               8080/TCP
    Args:
      -cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1 >/dev/null
      -port=8080
    Limits:
      cpu:      10m
      memory:   20Mi
    Requests:
      cpu:                      10m
      memory:                   20Mi
    State:                      Running
      Started:                  Mon, 19 Dec 2016 16:04:04 +0800
    Ready:                      True
    Restart Count:              0
    Environment Variables:      <none>
Conditions:
  Type          Status
  Initialized   True
  Ready         False
  PodScheduled  True
Volumes:
  etcd-storage:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  default-token-ow6av:
    Type:       Secret (a volume populated by a Secret)
    SecretName: default-token-ow6av
QoS Tier:       Guaranteed
Events:
  FirstSeen     LastSeen        Count   From                            SubobjectPath                   Type            Reason          Message
  ---------     --------        -----   ----                            -------------                   --------        ------          -------
  28m           28m             1       {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{skydns}         Normal          Created         Created container with docker id d1886ac83e91
  28m           28m             1       {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{kube2sky}       Normal          Created         Created container with docker id a444c75c1521
28m           28m             1       {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{kube2sky}       Normal          Started         Started container with docker id a444c75c1521
  28m           28m             1       {default-scheduler }                                            Normal          Scheduled       Successfully assigned kube-dns-v10-o4x5m to 0c-c4-7a-82-c5-bc
  28m           28m             1       {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{skydns}         Normal          Started         Started container with docker id d1886ac83e91
  28m           28m             1       {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{healthz}        Normal          Started         Started container with docker id 122ab46babd1
  28m           28m             1       {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{healthz}        Normal          Created         Created container with docker id 122ab46babd1
  28m           28m             1       {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{healthz}        Normal          Pulled          Container image "bootstrapper:5000/typhoon1986/exechealthz:1.0" already present on machine
  27m           27m             1       {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{kube2sky}       Normal          Started         Started container with docker id b8ef33bfdbe7
  27m           27m             1       {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{kube2sky}       Normal          Created         Created container with docker id b8ef33bfdbe7
  27m           27m             1       {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{skydns}         Normal          Created         Created container with docker id 0fdb839ccdf9
  27m           27m             1       {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{skydns}         Normal          Started         Started container with docker id 0fdb839ccdf9
  27m           27m             1       {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{skydns}         Normal          Killing         Killing container with docker id d1886ac83e91: pod "kube-dns-v10-o4x5m_kube-system(b4922818-c5c1-11e6-86f1-002590c0f780)" container "skydns" is unhealthy, it will be killed and re-created.
  26m           26m             1       {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{skydns}         Normal          Killing         Killing container with docker id 0fdb839ccdf9: pod "kube-dns-v10-o4x5m_kube-system(b4922818-c5c1-11e6-86f1-002590c0f780)" container "skydns" is unhealthy, it will be killed and re-created.
  26m           26m             1       {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{skydns}         Normal          Created         Created container with docker id e112bc22358d
  26m           26m             1       {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{skydns}         Normal          Started         Started container with docker id e112bc22358d
  26m           26m             1       {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{skydns}         Normal          Started         Started container with docker id be79e10842af
  26m           26m             1       {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{skydns}         Normal          Created         Created container with docker id be79e10842af
  26m           26m             1       {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{skydns}         Normal          Killing         Killing container with docker id e112bc22358d: pod "kube-dns-v10-o4x5m_kube-system(b4922818-c5c1-11e6-86f1-002590c0f780)" container "skydns" is unhealthy, it will be killed and re-created.
  26m           26m             4       {kubelet 0c-c4-7a-82-c5-bc}                                     Warning         FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "kube2sky" with CrashLoopBackOff: "Back-off 10s restarting failed container=kube2sky pod=kube-dns-v10-o4x5m_kube-system(b4922818-c5c1-11e6-86f1-002590c0f780)"

  26m   26m     1       {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{kube2sky}       Normal  Started         Started container with docker id 9e40142d8b3f
  26m   26m     1       {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{kube2sky}       Normal  Created         Created container with docker id 9e40142d8b3f
  25m   25m     1       {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{skydns}         Normal  Killing         Killing container with docker id be79e10842af: pod "kube-dns-v10-o4x5m_kube-system(b4922818-c5c1-11e6-86f1-002590c0f780)" container "skydns" is unhealthy, it will be killed and re-created.
  25m   25m     1       {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{skydns}         Normal  Created         Created container with docker id d183a5469c7f
  25m   25m     1       {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{skydns}         Normal  Started         Started container with docker id d183a5469c7f
  25m   25m     1       {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{skydns}         Normal  Killing         Killing container with docker id d183a5469c7f: pod "kube-dns-v10-o4x5m_kube-system(b4922818-c5c1-11e6-86f1-002590c0f780)" container "skydns" is unhealthy, it will be killed and re-created.
  25m   25m     3       {kubelet 0c-c4-7a-82-c5-bc}                                     Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "skydns" with CrashLoopBackOff: "Back-off 40s restarting failed container=skydns pod=kube-dns-v10-o4x5m_kube-system(b4922818-c5c1-11e6-86f1-002590c0f780)"

  25m   25m     1       {kubelet 0c-c4-7a-82-c5-bc}             Warning FailedSync      Error syncing pod, skipping: [failed to "StartContainer" for "skydns" with CrashLoopBackOff: "Back-off 40s restarting failed container=skydns pod=kube-dns-v10-o4x5m_kube-system(b4922818-c5c1-11e6-86f1-002590c0f780)"
, failed to "StartContainer" for "kube2sky" with CrashLoopBackOff: "Back-off 20s restarting failed container=kube2sky pod=kube-dns-v10-o4x5m_kube-system(b4922818-c5c1-11e6-86f1-002590c0f780)"
]
  24m   24m     1       {kubelet 0c-c4-7a-82-c5-bc}             Warning FailedSync      Error syncing pod, skipping: [failed to "StartContainer" for "kube2sky" with CrashLoopBackOff: "Back-off 20s restarting failed container=kube2sky pod=kube-dns-v10-o4x5m_kube-system(b4922818-c5c1-11e6-86f1-002590c0f780)"
, failed to "StartContainer" for "skydns" with CrashLoopBackOff: "Back-off 40s restarting failed container=skydns pod=kube-dns-v10-o4x5m_kube-system(b4922818-c5c1-11e6-86f1-002590c0f780)"
]
  23m   23m     1       {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{skydns} Normal  Killing         Killing container with docker id 4754613f3cbc: pod "kube-dns-v10-o4x5m_kube-system(b4922818-c5c1-11e6-86f1-002590c0f780)" container "skydns" is unhealthy, it will be killed and re-created.
  23m   23m     3       {kubelet 0c-c4-7a-82-c5-bc}                             Warning FailedSync      Error syncing pod, skipping: [failed to "StartContainer" for "kube2sky" with CrashLoopBackOff: "Back-off 40s restarting failed container=kube2sky pod=kube-dns-v10-o4x5m_kube-system(b4922818-c5c1-11e6-86f1-002590c0f780)"
, failed to "StartContainer" for "skydns" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=skydns pod=kube-dns-v10-o4x5m_kube-system(b4922818-c5c1-11e6-86f1-002590c0f780)"
]
  23m   22m     6       {kubelet 0c-c4-7a-82-c5-bc}             Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "skydns" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=skydns pod=kube-dns-v10-o4x5m_kube-system(b4922818-c5c1-11e6-86f1-002590c0f780)"

  22m   22m     1       {kubelet 0c-c4-7a-82-c5-bc}             Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "kube2sky" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=kube2sky pod=kube-dns-v10-o4x5m_kube-system(b4922818-c5c1-11e6-86f1-002590c0f780)"

  21m   21m     1       {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{skydns} Normal  Killing         Killing container with docker id 8ef77de2611d: pod "kube-dns-v10-o4x5m_kube-system(b4922818-c5c1-11e6-86f1-002590c0f780)" container "skydns" is unhealthy, it will be killed and re-created.
  21m   20m     7       {kubelet 0c-c4-7a-82-c5-bc}                             Warning FailedSync      Error syncing pod, skipping: [failed to "StartContainer" for "kube2sky" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=kube2sky pod=kube-dns-v10-o4x5m_kube-system(b4922818-c5c1-11e6-86f1-002590c0f780)"
, failed to "StartContainer" for "skydns" with CrashLoopBackOff: "Back-off 2m40s restarting failed container=skydns pod=kube-dns-v10-o4x5m_kube-system(b4922818-c5c1-11e6-86f1-002590c0f780)"
]
  20m   19m     5       {kubelet 0c-c4-7a-82-c5-bc}             Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "skydns" with CrashLoopBackOff: "Back-off 2m40s restarting failed container=skydns pod=kube-dns-v10-o4x5m_kube-system(b4922818-c5c1-11e6-86f1-002590c0f780)"

  19m   18m     3       {kubelet 0c-c4-7a-82-c5-bc}             Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "kube2sky" with CrashLoopBackOff: "Back-off 2m40s restarting failed container=kube2sky pod=kube-dns-v10-o4x5m_kube-system(b4922818-c5c1-11e6-86f1-002590c0f780)"

  18m   18m     1       {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{skydns} Normal  Killing         Killing container with docker id 1a2906c580fe: pod "kube-dns-v10-o4x5m_kube-system(b4922818-c5c1-11e6-86f1-002590c0f780)" container "skydns" is unhealthy, it will be killed and re-created.
  18m   17m     6       {kubelet 0c-c4-7a-82-c5-bc}                             Warning FailedSync      Error syncing pod, skipping: [failed to "StartContainer" for "kube2sky" with CrashLoopBackOff: "Back-off 2m40s restarting failed container=kube2sky pod=kube-dns-v10-o4x5m_kube-system(b4922818-c5c1-11e6-86f1-002590c0f780)"
, failed to "StartContainer" for "skydns" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=skydns pod=kube-dns-v10-o4x5m_kube-system(b4922818-c5c1-11e6-86f1-002590c0f780)"
]
  12m   12m     1       {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{skydns}         Normal  Killing         Killing container with docker id 5b3c8fc9aff0: pod "kube-dns-v10-o4x5m_kube-system(b4922818-c5c1-11e6-86f1-002590c0f780)" container "skydns" is unhealthy, it will be killed and re-created.
  19m   12m     12      {kubelet 0c-c4-7a-82-c5-bc}                                     Warning FailedSync      (events with common reason combined)
  28m   4m      9       {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{kube2sky}       Normal  Pulled          Container image "bootstrapper:5000/yancey1989/kube2sky:1.14" already present on machine
  16m   3m      15      {kubelet 0c-c4-7a-82-c5-bc}                                     Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "skydns" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=skydns pod=kube-dns-v10-o4x5m_kube-system(b4922818-c5c1-11e6-86f1-002590c0f780)"

  14m   1m      8       {kubelet 0c-c4-7a-82-c5-bc}             Warning FailedSync      Error syncing pod, skipping: [failed to "StartContainer" for "skydns" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=skydns pod=kube-dns-v10-o4x5m_kube-system(b4922818-c5c1-11e6-86f1-002590c0f780)"
, failed to "StartContainer" for "kube2sky" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=kube2sky pod=kube-dns-v10-o4x5m_kube-system(b4922818-c5c1-11e6-86f1-002590c0f780)"
]
  15m   59s     42      {kubelet 0c-c4-7a-82-c5-bc}             Warning FailedSync      Error syncing pod, skipping: [failed to "StartContainer" for "kube2sky" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=kube2sky pod=kube-dns-v10-o4x5m_kube-system(b4922818-c5c1-11e6-86f1-002590c0f780)"
, failed to "StartContainer" for "skydns" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=skydns pod=kube-dns-v10-o4x5m_kube-system(b4922818-c5c1-11e6-86f1-002590c0f780)"
]
  12m   9s      4       {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{skydns}         Normal  Killing         (events with common reason combined)
  24m   9s      15      {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{kube2sky}       Normal  Started         (events with common reason combined)
  24m   9s      15      {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{kube2sky}       Normal  Created         (events with common reason combined)
 28m   9s      14      {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{skydns}         Normal  Pulling         pulling image "bootstrapper:5000/typhoon1986/skydns:latest"
  28m   9s      14      {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{skydns}         Normal  Pulled          Successfully pulled image "bootstrapper:5000/typhoon1986/skydns:latest"
  27m   9s      15      {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{skydns}         Warning Unhealthy       Liveness probe failed: HTTP probe failed with statuscode: 503
  27m   9s      15      {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{skydns}         Warning Unhealthy       Readiness probe failed: HTTP probe failed with statuscode: 503
  13m   7s      24      {kubelet 0c-c4-7a-82-c5-bc}                                     Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "kube2sky" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=kube2sky pod=kube-dns-v10-o4x5m_kube-system(b4922818-c5c1-11e6-86f1-002590c0f780)"

  26m   7s      218     {kubelet 0c-c4-7a-82-c5-bc}     spec.containers{kube2sky}       Warning BackOff Back-off restarting failed docker container
```
