### ISSUE TITLE
need to add service account for kube-dns when using RBAC

### ISSUE THREAD

**Issue by typhoonzero** [k8sp/sextant#570]
Add this line in template

https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/kubedns-controller.yaml.in#L171

then create service account under `kube-system` namespace:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-dns
```

**Comment by typhoonzero** [comment]
And also for `v1.6.2` we have to add "get" permission for kube-dns service account:

run `kubectl replace -f xxx` to update the clusterrole:

```yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:kube-dns
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  verbs:
  - list
  - watch
  - get
```
