### ISSUE TITLE
centos 7.3.1611 installation issue

### ISSUE THREAD

**Issue by putcn** [k8sp/sextant#576]
node installation is stuck at the screen as follows. and even when I manually selected in option 4, the option 4 is still marked with "!", and can not move on with the installation.
![screen shot 2017-09-27 at 10 34 32 am](https://user-images.githubusercontent.com/2062926/30928662-095577fe-a371-11e7-867e-bad1ccd9a987.png)

my cluster desc is as follows (mirror site 10.0.3.1 is a locally hosted file server to provide centos images)

```
# NOTICE:
# 1. If you change version of them such as kube,centos, it's better to 
#    delete the bsroot directory because it does't update a exist file.
#    or do what you know.
# 2. Please check that $mirror_site/$centos_version/(isos|os) exist

bootstrapper: 10.0.3.3
subnet: 10.0.3.0
netmask: 255.255.255.0
iplow: 10.0.3.7
iphigh: 10.0.3.252
routers: [10.0.3.1]
broadcast: 10.0.3.255
nameservers: [10.0.3.253]
upstreamnameservers: [8.8.8.8, 8.8.4.4]
domainname: "ail.unisound.com"
dockerdomain: "bootstrapper"
k8s_service_cluster_ip_range: 10.100.0.0/24
k8s_cluster_dns: 10.100.0.10

#start pxe?
start_pxe: y

# Flannel backend only support "host-gw", "vxlan" and "udp" for now.
flannel_backend: "host-gw"

# coreos_channel can be configured as stable, alpha, beta.
coreos_channel: "stable"

# coreos_version can be configured as the special version num or "current"
coreos_version: "1122.2.0"

# centos version
download_kernel: y
# configure mirror_site, sunch as:
#   http://mirrors.163.com/centos
mirror_site: http://10.0.3.1/centos
# Configure the centos version for isos and rpms
centos_version: "7.3.1611"

# gpu drivers version
set_gpu: n
gpu_drivers_version: "375.26"

ingress_hostnetwork: true

# Ntpserver set_ntp option for the cluster configuration.
set_ntp: y
# Set DNSMASQ DHCP least time
lease: "infinite"

#OS type: CentOS or CoreOS
os_name: "CentOS"

# Centos repository: default repository for bootstrapper,
# If you need to configure the other repository, need to open the configuration switch.
# Currently supports only add 163 repository.
# for example: 163 repo:
# set_yum_repo: "mirrors.163.com"
set_yum_repo: "mirrors.aliyun.com"

# kube master ip, there should be cluster ip
kube_master_ip:
    - "10.100.0.1"
    - "192.168.61.73"
    - "192.168.48.23"
kube_master_dns:
    - "aa-bb-cc-dd"

coreos:
  reboot_strategy: "etcd-lock"
  start_time: "03:00"
  time_length: "3h"

ceph:
  zap_and_start_osd: n
  osd_journal_size: 5000

images:
  hyperkube: "gcr.io/google_containers/hyperkube-amd64:v1.6.2"
  pause: "gcr.io/google_containers/pause-amd64:3.0"
  flannel: "quay.io/coreos/flannel:v0.7.1-amd64"
  ingress: "gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.3"
  default_backend: "gcr.io/google_containers/defaultbackend:1.0"
  kubedns: "gcr.io/google_containers/kubedns-amd64:1.9"
  kubednsmasq: "gcr.io/google_containers/kube-dnsmasq-amd64:1.4"
  healthz: "gcr.io/google_containers/exechealthz-amd64:1.2"
  addon_manager: "gcr.io/google_containers/kube-addon-manager-amd64:v6.4-beta.1"
  ceph: "typhoon1986/ceph-daemon:tag-build-master-jewel-ubuntu-14.04-fix370"
  ntp: "redaphid/docker-ntp-server"
  heapster: "kubernetes/heapster:canary"
  grafana: "lupan/heapster_grafana:v2.6.0-2"
  influxdb: "lupan/heapster_influxdb:v0.5"
  dashboard: "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.0"


# if you wan't use mac as hostname, please delete cur_host_name or 
# set them to ""
nodes:
  - mac: "08:00:27:00:B2:98"
    cur_host_name: "api"
    ceph_monitor: y
    kube_master: y
    etcd_member: y
    ingress_label: y
```
